### ISSUE TITLE
Clean all aborted snapshots?

### ISSUE THREAD

**Issue by ywelsch-t** [imotov/elasticsearch-snapshot-cleanup#1]
Is there a particular reason to only clean up aborted snapshot for nodes that are not running anymore? (i.e. check `clusterState.nodes().get(nodeId) == null`)

Ran into the issue where backup was stuck with `clusterState.nodes().get(nodeId) != null`.

**Comment by imotov** [comment]
Yes, it might not be safe to delete snapshots on the nodes that are currently running, we need to wait until the process finishes there and if it's stuck for some reason, we need to restart these nodes. This script should be no longer needed by the way. Its functionality was already incorporated into https://github.com/elastic/elasticsearch/pull/9981
