### ISSUE TITLE
Broken test?

### ISSUE THREAD

**Issue by allthedrones** [imotov/elasticsearch-snapshot-cleanup#5]
For Elasticsearch >= 1.6.0, I think the tests are broken, possibly by https://github.com/elastic/elasticsearch/issues/15427 ?

**Comment by imotov** [comment]
If you have an issue with 1.6.0 or above, this cleanup utility is unlikely to help, because its functionality is already incorporated into elasticsearch itself (via elastic/elasticsearch#11450).
